import styled from 'styled-components';
import {
    alignContent,
    alignItems,
    alignSelf,
    backgroundImage,
    borderRadius,
    borders,
    bottom,
    color,
    display,
    flex,
    flexBasis,
    flexDirection,
    flexWrap,
    fontFamily,
    fontSize,
    fontStyle,
    fontWeight,
    gridArea,
    gridAutoColumns,
    gridAutoFlow,
    gridAutoRows,
    gridColumn,
    gridColumnGap,
    gridGap,
    gridRow,
    gridRowGap,
    gridTemplateAreas,
    gridTemplateColumns,
    gridTemplateRows,
    height,
    justifyContent,
    left,
    lineHeight,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    order,
    position,
    right,
    space,
    textAlign,
    top,
    width,
    zIndex
} from 'styled-system';
import { textTransform } from './utils/system';

type BoxProps = {
    as?: string;
};

const Box: React.FC<any> = styled.div(
    {
        boxSizing: 'border-box'
    },
    alignContent,
    alignItems,
    alignSelf,
    backgroundImage,
    borders,
    borderRadius,
    bottom,
    color,
    display,
    flex,
    flexBasis,
    flexDirection,
    flexWrap,
    fontFamily,
    fontSize,
    fontStyle,
    fontWeight,
    gridGap,
    gridRowGap,
    gridColumnGap,
    gridColumn,
    gridRow,
    gridArea,
    gridAutoFlow,
    gridAutoRows,
    gridAutoColumns,
    gridTemplateRows,
    gridTemplateColumns,
    gridTemplateAreas,
    height,
    justifyContent,
    left,
    lineHeight,
    maxHeight,
    maxWidth,
    minHeight,
    minWidth,
    order,
    position,
    right,
    space,
    textAlign,
    textTransform,
    top,
    width,
    zIndex
);

export default Box;
